package main

const (
	Name                string = "90s"
	BodyFont            string = "poppins"
	TitleFont           string = "oswald"
	Border              bool   = true
	BorderRadius        string = "-2xl"
	Primary             string = "purple-500"
	PrimaryDark         string = "purple-400"
	Secondary           string = "sky-500"
	SecondaryDark       string = "blue-400"
	Surface             string = "neutral-100"
	SurfaceDark         string = "neutral-800"
	SurfaceAlt          string = "neutral-200"
	SurfaceAltDark      string = "neutral-900"
	OnSurface           string = "neutral-800"
	OnSurfaceStrong     string = "black"
	OnSurfaceDark       string = "neutral-300"
	OnSurfaceStrongDark string = "neutral-100"
	OnPrimary           string = "white"
	OnPrimaryDark       string = "black"
	OnSecondary         string = "white"
	OnSecondaryDark     string = "black"
	Outline             string = "neutral-300"
	OutlineDark         string = "neutral-700"
	OutlineStrong       string = "neutral-800"
	OutlineStrongDark   string = "neutral-300"
	Danger              string = "pink-500"
	OnDanger            string = "black"
	Info                string = "cyan-500"
	OnInfo              string = "black"
	Warning             string = "yellow-300"
	OnWarning           string = "black"
	Success             string = "teal-400"
	OnSuccess           string = "black"
)
